### ISSUE TITLE
Test and monitoring flows and extensions

### ISSUE THREAD

**Issue by dband** [directus-community/guest-authoring#1]
### What is your idea?

Currently, there is no guide on how to monitor or test Directus applications. In order to tackle the reliability of more complex use cases like BaaS or internal apps this is a mandatory step. In this post, I want to share an approach that I created for Directus in the last 6 months.

1. Introduction
1.1 Why bother at all?
1.2 Directus Components under test
2. A poor man's approach
2.1 Setup Integration and end2end tests
2.2. Using activity tracking of flows to test "units"
2.3. Creating a monitoring/logging pipeline
2.4. Listening to events and raise concerns
3. Conclusions

I will think of the estimated time I need.

### What are the key takeaways from your post?

- Show that Directus can be used to create reliable data-driven applications
- Provide an approach to logging and monitoring without using third-party software

### What type of post is this?

Tips, Tricks, or Best Practice

### Country of residence

Germany

### Terms & Conditions

- [x] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Yup, I'm into this. There's a few notes I have: 

1. For a title I'd make a slight revision to "Testing and Monitoring Flows & Extensions"
2. Not a big fan of "A poor man's approach" for a few reasons. I think that the four items within it can just become subheadings. Something like:

```
Introduction paragraph or two

## Setup Integrations and End-To-End Tests

Section content

## Using Activity Tracking To Test "Units" 

Section content

...and so on.
```

I'm otherwise all happy with this and, based on our face-to-face convo yesterday, happy to kick this off. 

We can pay $350 for this post. Only other thing I need to approve this and kick it off with you is that estimated timeline for a first draft. In an ideal world, this can happen within 1-2 weeks. Does that sounds achievable?

**Comment by dband** [comment]
Sure, I'll try to create a draft this weekend. I will have to share some code snippets. Apart from putting those in the post, I would make the full setup available in my personal repository. Is that ok?

**Comment by phazonoverload** [comment]
That’s fantastic. Feel free to make it on your own and then I will fork it into this org. I’m happy for you to link to your version in the blog post.

**Comment by phazonoverload** [comment]
Hey @dband how's this coming along?

**Comment by dband** [comment]
> Hey @dband how's this coming along? 

Coding wise, I am finishing the tests. I am pushing my code later today, and link it here, but I still have to write down everything. 

Since I overhauled the application it took me longer than expected. Also I have some problems with the websocket connection, which seems to terminate consistently after the first ping. Might not be an issue for the article, but still annoying.

**Comment by phazonoverload** [comment]
I think it's best if the post encompasses everything someone needs to know - so take the time to help them set it up.
