### ISSUE TITLE
Reverse Proxy to Directus using IIS

### ISSUE THREAD

**Issue by ElementumIT** [directus-community/guest-authoring#10]
### What is your idea?

This article would help those of us who have to use IIS on a windows server get Directus set up.  It took me a lot of googling around to put all the pieces together. I can also document how I was able to get Directus to run on a sub-directly like https://www.mycompany.com/Directus.  There was some tricky parts to getting that to work right.  But easy once you know how!

### What are the key takeaways from your post?

How to reverse proxy from IIS to Directus and how to run Directus on a sub-directory. 

### What type of post is this?

Self-Hosting Guide

### Country of residence

United States

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by ElementumIT** [comment]
Oh, i should add, I would only be prepared to write this from the point of view of someone running Directus without Docker involved.  Docker on a windows server is another can of worms I haven't opened.

**Comment by phazonoverload** [comment]
That’s a shame because I was going to, pending a couple of other questions, be up for this post. 

I firmly do not want to publish any material that promotes or explains how to run or host Directus without Docker. The short term win is often far exceeded by environment-specific configuration issues which can also change over time. 

So, for that reason, I don’t think this is going to be a post idea that we can accept. I sincerely appreciate you taking the time to put it together though.

**Comment by ElementumIT** [comment]
No problem, I completely understand.  I would actually much prefer to run Directus on Docker, especially if that's generally considered to be the better way to go.  I will take another look at how I can do that in a windows environment and if I figure it out I will circle back!  

Thanks for your response.  I am very excited about Directus, it seems like the perfect combination of features for what I am looking to do.
