### ISSUE TITLE
Syncing Directus and Google Calendar With Directus Automate And Google Apps Script

### ISSUE THREAD

**Issue by yureckey** [directus-community/guest-authoring#12]
### What is your idea?

I'm a freelancer with broad range of specializations, one of them - workflow automations and low-code/no-code solutions (and code too):
- Google Apps Script (automations of Google Spreadsheet/Doc/Drive/Calendar/etc)
- n8n, Zapier, Make, Pipedream (workflow automations)
- Retool, Appsmith (internal Apps)
- App platforms (Draftbit, FlutterFlow)

Some of these are open-source, some have free plans, some paid.
Will you be interested in a blog posts describing Integration of these Tools/Services and Directus?

### What are the key takeaways from your post?

Depends on the topic

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Israel

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
There's a load of ideas in here. The workflow automations doesn't make sense to me, because it's just make an API request to either Directus directly or to a Flow. Internal Apps suffer the same fate in my mind because Directus Insights *is* is an internal app builder. 

The first set could be interesting though, starting possibly with calendar. How do you feel about `Integrating Google Calendar With Directus`?

We can decide on what 'integrate' means in this issue. Could be either or both of:
- Directus Item Create/Update/Delete -> Cal items 
- Cal item Create/Update/Delete -> Directus item

**Comment by yureckey** [comment]
Yes, let's suppose that we have Directus collection with dedicated datetime field. The interesting project would be to have it synced with Google Calendar - part 1, when Directus item created/updated/deleted then event in google calendar created/updated/deleted. And part 2 - vice versa, when google calendar event created/updated/deleted then item in Directus collection is created/updated/deleted. I've spent some time on initial research - it's not that quick and easy to implement, but seems doable (I didn't yet finish mvp scripts/flows, but some parts are already working).

**Comment by phazonoverload** [comment]
Yeah that works for me, though I'd want to do it as a single post. This idea of two-way Google Calendar syncing is one that I know there's lots of interest in. I can pay $350 for this post. 

If that sounds good, when do you think you could have a draft done by? I won't hold you to it - but it's useful to get an idea of when I would need to set aside time to review and publish this piece.

**Comment by yureckey** [comment]
Two-way sync in one post - that will be a lengthy post, but why not.
$350 as pay - can we make an agreement that when you'll check resulting post+code, 
if you'll find it worthy, you'll increase to $500?
(Or we can discuss how to make it less complex)
I plan to work on it this week.

**Comment by phazonoverload** [comment]
I don't think it is a terribly long or complex post: 

1. Set up a Directus project with a collection including a date.
2. Flow for create/update/delete item which checks if the item exists in GCal. If not, create. If yes, update or delete. 
3. Script on Google side runs when item is created/updated/deleted which triggers a second Directus Flow, which does the opposite and creates/updates/deletes a Directus item. 

Given what I perceive the scope of complexity of this post, the rate isn't negotiable. The Directus Guest Author program is also one which aims to enrich your own technical writing skills. If that doesn't work for you, that's totally ok and no bad feeling - we can just leave this here.

**Comment by yureckey** [comment]
On a high level - yes, you right. But complexity comes from sub-steps.
I've spent some time already starting to implement it, so I can say with more confidence:

There have to be some common id that allows pin-point events/items. Otherwise if syncing is by, say, title and date it isn't possible to sync event when user changes its title and date.
So, additional work related to work with this id
2. "_Flow for create/update/delete item which checks if the item exists in GCal. If not, create. If yes, update or delete_":
it seems to be more or less straightforward Flows.

3. "_Script on Google side runs when item is created/updated/deleted which triggers a second Directus Flow_"
google calendar event change trigger - there is no out-of-box simple solution. It's either google apps script time trigger (cons: delay in reaction time to not deplete quota, additional work to keep track of events)
Or it's usage of calendar watch events notification, which requires additional step as Directus Webhook Flow that will proxy call to our google apps script, cause Apps Script webhook can't read incoming headers and Google event push notification only have info in headers (plus, probably I need to provide functions to cancel and renew notification Channel). 
In both cases, additional work in script required to actually get changed events (it is not received in notification)
There is functionality to list google events by SyncToken (it gives list of changed events since the last SyncToken). The complication here - how to differentiate events updated/created/deleted by User from the events updated/created/deleted by the script initiated from Directus Flow (there is no checkbox "genereate event"). I'm kinda stuck on this for a moment, trying to find an elegant solution, but it seems there is no elegent, only ugly ones (like keep the id+timestamp of update from script and in the watch event ignore change if it is on that id+timestamp)

Also things that probably will be out of scope to keep project simple:
- bulk items created/updated in Directus
- recurring events in Google Calendar

Anyway, I understand your position and your concerns. I'm fine with originally proposed payment.

**Comment by yureckey** [comment]
ok, the script/flows is about 95% ready. I've recorded a short demo, so you can have a glance of flows and script:
https://www.loom.com/share/a0e0ce8886cc488494988dc64b9a4d0a?sid=0f1cca18-05fa-4e0d-aea9-4ea74392dafc

**Comment by phazonoverload** [comment]
Firstly I can't believe you used a Google Sheet for logging. I kinda love how ridiculous it is. 😛 

I typically wouldn't negotiate the fee we can pay for posts as I base them in a pretty good vibe for the effort needed, but I do agree with you now I've seen your Loom video that my assumptions were incorrect. We can pay $500 for this post - I think that's fair. 

So as it comes to the writing part of the project, I think it should probably be structured as follows: 

1. Introduction
2. Setup (Directus project config, Google Sheet Document setup incl config)
3. Create Google Calendar Events From Directus
4. Edit Google Calendar Events From Directus
5. Delete Google Calendar Events From Directus
6. Create Directus Items From Google Calendar
7. Edit Directus Items From Google Calendar
8. Delete Directus Items From Google Calendar
9. Summary

What do you think? And when do you think you could have a first draft?

**Comment by yureckey** [comment]
That's great, thanks.
Couple of questions:
I've read that directus will have launch week next week. Could there be something related to flows that will improve my project? Should I wait maybe?
Second - can we have more quick communication, like DM in discord or something, so there is no several days waiting if i have some quick questing regarding writing

**Comment by phazonoverload** [comment]
Yup DM in Discord is fine for back and forth. I am pretty heads-down in Leap Week prep at the moment so I might not be the quickest to reply, but it should be quicker than here. 

Your project won't be impacted by next week's announcements 😄
