### ISSUE TITLE
Building a Commenting System With Directus Connect

### ISSUE THREAD

**Issue by Rusya13** [directus-community/guest-authoring#13]
### What is your idea?

I am looking to improve my website of browser games (https://ruslan.rocks) by adding more information about each game's statistics, such as likes, comments, and views.

I have previously worked with Directus and believe it could be a great fit for this project. I am also interested in exploring the possibility of connecting via websockets if Directus now supports it.

This solution could be beneficial for other websites looking to enhance user engagement.

Overall it will be an interesting case for the community and for the website owners with the similar niche.

### What are the key takeaways from your post?

How to build and integrate engagement solutions for your project with Directus.

### What type of post is this?

Tips, Tricks, or Best Practice

### Country of residence

Australia

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
In an effort to scope this down a bit, I think it could be interesting to write something specifically around an liking/comment system. 

Could you put together an outline for this? I think it could probably be about setting up a sensible data model and then how to use the API to fetch data. I don't think this needs to include a front-end component, as that's quite subjective to the reader. I can pay $250 for this post.

Let me know what you think!

**Comment by phazonoverload** [comment]
Also, I think this would be more useful if not attached to the games website when written, but as a more abstract piece: 

- Given a list of items
- Items can have likes added/removed
- Items can have comments

**Comment by Rusya13** [comment]
Thank you for the feedback. It makes sense. I will start working on it.

**Comment by phazonoverload** [comment]
Excellent. What do you think is a reasonable guess at a first draft being done?

**Comment by Rusya13** [comment]
If there's no rush, I can work on it in the next two weeks. How does that sound?

**Comment by phazonoverload** [comment]
That works for me. The process is in the readme of this repo 😄

**Comment by phazonoverload** [comment]
Hey @Rusya13 how is this looking?

**Comment by Rusya13** [comment]
Hi @phazonoverload . Sorry for the delay. I'm aiming to have a draft for the review next Monday.

**Comment by phazonoverload** [comment]
Hey @Rusya13 it's been a while since this one first came up and was approved. Can I get a indication of if you're still working on it or whether you're no longer interested? 

If you're up for it - can I get an indication of when you might have a first draft done?

**Comment by phazonoverload** [comment]
Given the lack of updates I'm going to assume you no longer have time for this. I'm going to close this issue out and remove it from our content schedule. If things change in the future and you wish to do this guest post, please let me know and I'll assess whether it works for us in terms of priorities, timeline, and budget.
