### ISSUE TITLE
Hosting a Directus Application on an Ubuntu Server and Linking It to a Custom Domain

### ISSUE THREAD

**Issue by koredeycode** [directus-community/guest-authoring#14]
### What is your idea?

The idea is to show how to remotely host a Directus instance for example like I have here: https://directus.koredeycode.tech/.

The tutorial covers a range of topics, including setting up Docker, configuring Docker Compose, using Nginx as a reverse proxy, securing the application with SSL, and running the application as a background service.

### What are the key takeaways from your post?

- Readers will gain technical proficiency in deploying a Directus application within a Docker container on an Ubuntu Linux server.
- Understanding of Docker, Docker Compose, Nginx configuration, and SSL setup for secure web hosting.

### What type of post is this?

Self-Hosting Guide

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This topic sounds good and I actually think those five topics are the main subheadings throughout. I can pay $350 for this post. If interested, just let me know when you think you can have a first draft ready - the workflow is to fork this repo, add your work in markdown files, and then submit a PR. We use the PR to perform the review.

**Comment by koredeycode** [comment]
Thank you for your feedback. 

I can actually work with that.

Actually, I have been actively working the initial draft and expect to have the first version ready within a week.

**Comment by koredeycode** [comment]
Hi, can you please approve this so I can create a PR.
