### ISSUE TITLE
How to integrate Okta SSO with the SAML platform in a Directus application

### ISSUE THREAD

**Issue by MaxJacobs213** [directus-community/guest-authoring#15]
### What is your idea?

I have spent a few days trying to get SSO with Okta to work correctly with the SAML provider. There were a lot of things that were not obvious and undocumented. I had to research the source code of the project and read the Okta docs to understand what settings in Okta and environment variables I need to set. I believe this guide will be useful to developers.

### What are the key takeaways from your post?

- Why I chose SAML over OpenId
- How to create an app in Okta step by step
- Which parameters must be specified in Okta with an explanation of why in order for the directus application to correctly authorize the user
- What settings need to be made on the Directus application side

### What type of post is this?

Other

### Country of residence

Ukraine

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This is a good topic and I'd love to have you write it. The only thing I would perhaps skip from your key takeaways is the first one - let's assume that the reader has already made the grounded decision.

I can pay $250 for this post. If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by MaxJacobs213** [comment]
@phazonoverload Thanks, I agree about the first point, I think I could have it done by the end of the week ( Oct 27th )

**Comment by phazonoverload** [comment]
Yeah that works for me.
