### ISSUE TITLE
Self host multiples directus instance with docker and nginx proxy manager to launch severals instances easily

### ISSUE THREAD

**Issue by LucasSovre** [directus-community/guest-authoring#19]
### What is your idea?

# The Idea

This article will be inspired by the stack I am using everyday for my self employ company , but I think it can really help people self host multiples directus , with each instance having their own domain name.

This stack is much easier than Kubernetes but offer a strong and scalable system to deploy severals directus instances.

This stack is based on a server (or multiples with docker swarm) where the user will use my portainer template to deploy: 
 - an automatic backuped Postgres database
 - a nginx with a GUI to easily add new domain name to new directus instance
 - many directus instances serve through the nginx with a secure docker network

 
## Scheme of my stack : 

```
               ┌───────────────────────────────────────────────────────────┐
               │                                                           │
               │     SERVER                                                │
               │                                                           │
┌────────┐     │   ┌────────┐                                              │
│        │     │   │        │  nginx_nework                                │
│ final  ├─────┼───┤ NGINX  ├─────┐   ┌─────────────┐    ┌───────────┐     │
│ user   │     │443│        │     │   │             │    │           │     │
└────────┘     │   └────────┘     ├───┤ Directus 1  ├─┬──┤ DATABASE  │     │
               │                  │   │             │ │  │           │     │
               │                  │   └─────────────┘ │  └───────────┘     │
               │                  │                   │                    │
               │                  │                   │ internal_network   │
               │                  │   ┌─────────────┐ │                    │
               │                  │   │             │ │                    │
               │                  ├───┤ Directus 2  ├─┤                    │
               │                  │   │             │ │                    │
               │                  │   └─────────────┘ │                    │
               │                  │                   │                    │
               │                  │                   │                    │
               │                  │   ┌─────────────┐ │                    │
               │                  │   │             │ │                    │
               │                  └───┤ Directus n  ├─┘                    │
               │                      │             │                      │
               │                      └─────────────┘                      │
               │                                                           │
               └───────────────────────────────────────────────────────────┘
```

### What are the key takeaways from your post?

- Deploy and use portainer
- Use nginx proxy manager to easily add SSL and domain name to directus
- Deploy severals directus without worries and for cheap

### What type of post is this?

Self-Hosting Guide

### Country of residence

France

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Hey! Thanks for taking the time to submit this idea. While it's interesting, we don't think it makes sense for the goals of our blog at the moment - which is around how widely applicable content is to our community members. If this changes in future, I'll let you know.
