### ISSUE TITLE
Deployment to DO APP Platform

### ISSUE THREAD

**Issue by BlackDahlia313** [directus-community/guest-authoring#2]
### What is your idea?

Create a dev blog that highlights how to quickly deploy/update and use Directus on the Digital Ocean App Platform.

This blog will receive updates overtime as new features are supported that enable quicker deployment. (do managed redis support)

### What are the key takeaways from your post?

- Deploy Directus using a dockerfile onto the DO app platform
- Create and connect a managed postgres DB that will be used.
- Create and connect DO Object Storage
- (optional) Create a redis droplet (until DO managed redis is supported)

### What type of post is this?

Self-Hosting Guide

### Country of residence

US

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Fab. Yes, as mentioned, very happy with this topic. Might be worth providing a basic sample Dockerfile as part of this.

**Comment by phazonoverload** [comment]
The only other thing missing is some kind of estimate for a first draft, so we can plan our time for reviewing and publishing.

**Comment by BlackDahlia313** [comment]
> The only other thing missing is some kind of estimate for a first draft, so we can plan our time for reviewing and publishing.

I am finishing it up now and will have the PR soon. Been really really sick out of nowhere and kinda lost a lot of time. :(

**Comment by BlackDahlia313** [comment]
Looks like everything is all in order. :)
