### ISSUE TITLE
Build Point of Sales (POS) Application using Directus and Next JS

### ISSUE THREAD

**Issue by kowalski21** [directus-community/guest-authoring#20]
### What is your idea?

The project aims to further showcase the power of directus
 in building powerful applications. In this project shows
 how directus as a headless cms to build Point of Sales Appliication to use in local stores
 to track sales, track inventory and utilize custom hooks to provide notification on
 inventory levels to store users. POS will enable users to generate reports on sales in excel formats
 by utilizing custom endpoints.
 Generate invoice either in pos format or a4 format.

### What are the key takeaways from your post?

 To learn how to model data using directus studio
 To learn how to write custom endpoints to further enrich your applications
 To learn how to write custom hooks to extend pos functionalities ( a hook to validate item in stock before creating an order item)
 To learn how to use directus sdk with next js app router 

### What type of post is this?

Full Project Build with Directus

### Country of residence

Ghana

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Hey @kowalski21 any update on the above?

**Comment by phazonoverload** [comment]
Given the lack of updates I'm going to assume you no longer have time for this. I'm going to close this issue out and remove it from our content schedule. If things change in the future and you wish to do this guest post, please let me know and I'll assess whether it works for us in terms of priorities, timeline, and budget.
