### ISSUE TITLE
Build an Authentication System with Nextjs and Directus

### ISSUE THREAD

**Issue by codejagaban** [directus-community/guest-authoring#21]
### What is your idea?

In this article, I'll go over how JavaScript developers can use Directus Auth and Nextjs, a frontend framework for creating an authentication system for Nextjs applications.

Key features of the project will include user registration, login, and password recovery mechanisms. The integration of Next.js with Directus will facilitate a smooth flow of data between the frontend and backend, providing developers with a comprehensive and efficient solution for implementing user authentication in their web applications.

In other to build a fully functional authentication system, I'll use the following tools:

- Directus for authenticating users and managing user rules and other essential functionalities
- Next.js as the frontend framework for the application
- Resend.com for transactional emails for sending emails.

At the end of the article, readers will be equipped with the knowledge and tools necessary to build a modern and secure authentication system with Nextjs and Directus

### What are the key takeaways from your post?

In this article, readers will learn:

- How to set up a project on Directus and connect it to a Nextjs application
- How to authenticate users for any Nextjs application using Directus Auth
- How to send transactional emails for an authentication system using Resend, React Emails, and Directus APIs
- Create a fully functional authentication system with, login, signup, forget password and recover password support

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This would be beneficial to our community. I have a question about how you plan to authenticate users - are you going to use something like Next Auth or build from scratch? My preference would be using the Next Auth package.

**Comment by 0xJamin** [comment]
> This would be beneficial to our community. I have a question about how you plan to authenticate users - are you going to use something like Next Auth or build from scratch? My preference would be using the Next Auth package.

Hi @phazonoverload  Yes I'll be using Next Auth package, I could also build from scratch, but using Next Auth would help to develop more robust solution.

**Comment by phazonoverload** [comment]
No need that’s my preference. When do you think you can have a draft by? We can pay €500 for this post.

**Comment by phazonoverload** [comment]
Of course but do those as separate issues so we can discuss each of them in isolation 😄

**Comment by 0xJamin** [comment]
Hi, @phazonoverload, the first draft of this article is ready
