### ISSUE TITLE
Implementing Discord automod feature within Directus

### ISSUE THREAD

**Issue by WoLfulus** [directus-community/guest-authoring#22]
### What is your idea?

A post teaching how to implement a Discord bot using Directus

### What are the key takeaways from your post?

It will guide the user on how to implement an automod feature for their Discord servers using only Directus features (hopefully without extensions too). 

### What type of post is this?

Full Project Build with Directus

### Country of residence

Brazil

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Can I get a high-level understanding of how this will end up working when it's all done?

**Comment by phazonoverload** [comment]
Any update on the above @WoLfulus?

**Comment by phazonoverload** [comment]
If your intention that the bot application would live in Directus?

**Comment by phazonoverload** [comment]
Just wanted to check you've seen the above @WoLfulus?

**Comment by phazonoverload** [comment]
Given the lack of updates I'm going to assume you no longer have time for this. I'm going to close this issue out and remove it from our content schedule. If things change in the future and you wish to do this guest post, please let me know and I'll assess whether it works for us in terms of priorities, timeline, and budget.
