### ISSUE TITLE
Mastering Directus: A Comprehensive Guide to Aggregation and Grouping Filters with Real-Life Blog Example

### ISSUE THREAD

**Issue by jaybharadia** [directus-community/guest-authoring#24]
### What is your idea?

In the ever-evolving landscape of web development, the need for robust content management systems (CMS) has become more apparent than ever. Directus stands out as a powerful choice, but navigating its intricacies, especially when it comes to complex **filters** with **nesting** and **logical** operators, can be a daunting task. 

Faced with the challenge of finding comprehensive guides that delve into the technical aspects of these features with real-life examples, I decided to take matters into my own hands and create a resource that developers can rely on to streamline their workflows and save precious time spent on endless Google searches and documentation trawls.

In this article, we will embark on a journey through the depths of Directus, exploring the nuances of aggregation and grouping filters. By providing a detailed and hands-on guide, I aim to empower developers to tackle real-life scenarios involving complex filter requirements without the frustration of trial and error.

### What are the key takeaways from your post?

The reader will learn about following points
- Aggregation & Grouping
- Filters
- SDK 11
- Blog Application Implementation with Directus

By creating this comprehensive guide, my goal is to contribute to the Directus community's knowledge base and make the development journey smoother for fellow developers.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

India

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
I'm actually really interested in an advanced filtering guide around a use case like this. However, I'm not interested in actually building a blog here. Instead, why not use it as the basis for making the queries, for example: 

> Using the blog example, assume you need to show xyz. Let's see how that would be done with [query feature]: 
> 
> Example here with explanation. 

How does this sound?

**Comment by jaybharadia** [comment]
> I'm actually really interested in an advanced filtering guide around a use case like this. However, I'm not interested in actually building a blog here. Instead, why not use it as the basis for making the queries, for example:
> 
> > Using the blog example, assume you need to show xyz. Let's see how that would be done with [query feature]:
> > Example here with explanation.
> 
> How does this sound?


Thank you 👍 for your swift response and your interest in an advanced filtering guide. I'm thrilled 🌟 to proceed with creating a practical guide based on real-world use cases, as per your suggestion.

To ensure I capture your vision accurately, could you kindly provide an example scenario for the advanced filtering guide, as mentioned in your message ❓ Having a specific use case will enable me to tailor the content more precisely and demonstrate the power of Directus queries effectively.

Additionally, when you refer to [query feature], could you please clarify if you are referring to Global Query Parameters or if there's a specific query feature within Directus that you have in mind ❓ This will help me focus on the exact functionalities you're interested in showcasing.

As discussed earlier, the guide will cover essential aspects such as:

**Date Filtering**
Explaining how to retrieve data using date filters, including options for filtering by month, year, and other available choices.

**Combining Filters**
Demonstrating the process of combining multiple filter queries to address complex scenarios effectively.

**Aggregation and Grouping**
Providing a comprehensive guide on obtaining counts using aggregation and grouping, with examples showcasing month-range and year-wise counts.

Your feedback and clarification on the example scenario and the specific query feature will be immensely helpful in crafting a guide that precisely meets your expectations.

Looking forward to your insights and further collaboration on this guide 😊

**Comment by jaybharadia** [comment]
Hi, @phazonoverload 
Let me know for a go ahead

**Comment by phazonoverload** [comment]
> could you kindly provide an example scenario for the advanced filtering guide
The scenario can be the blog as mentioned (or you can use a few), I just don't want any time wasted in actually building the blog application - just showing example advanced queries and how they meet the needs of the use case is enough. 

> Additionally, when you refer to [query feature], could you please clarify if you are referring to Global Query Parameters
Yes. 

I think your three proposed areas: date filtering, combining filters, and aggregation & grouping is great. 

We can pay $250 for this post. If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by jaybharadia** [comment]
Hey @phazonoverload , I have created first draft. Let me know once you **Approve** the issue to raise PR.

**Comment by phazonoverload** [comment]
That's now done @jaybharadia. Thanks, and look forward to seeing it.

**Comment by jaybharadia** [comment]
> That's now done @jaybharadia. Thanks, and look forward to seeing it.

Raised the PR https://github.com/directus-community/guest-authoring/pull/29
