### ISSUE TITLE
Building AI Venture

### ISSUE THREAD

**Issue by craigharman** [directus-community/guest-authoring#3]
### What is your idea?

Give a behind the scenes explanation on how I used Directus (and Nuxt) to create https://aiventure.craigharman.com - a text-based adventure game (in the style of Zork) with stories generated by Chat GPT.

The game uses:

- Directus flows as the back-end game engine
- The AI Directus extension: https://github.com/br41nslug/directus-extension-ai-pack
- Directus for Auth and user management
- https://nuxt-directus.netlify.app/

### What are the key takeaways from your post?

- Intricacies of using Chat GPT with Directus, eg. adding token limits (per user and per game), Chat GPT "system" messages, storing previous responses, ending the game
- Complicated flows with forking game logic, returning meaningful error messages, database design decisions to make flows easier
- Using Nuxt as the front end (via nuxt-directus extension)

### What type of post is this?

Full Project Build with Directus

### Country of residence

Australia

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Yes, great. There are many ways to write an article like this - some go step-by-step showing people how to do it, but I think that's both very long and unnecessary. 

What do you think about an overview of each of the components around how this application was put together, along with 2-3 small developer-focused points of interest. That could be implementing the email validation, how @br41nslug's extensions were used, or something else.

**Comment by craigharman** [comment]
Hi Kevin, I totally agree! I think a broad overview of all the components and then focus on email validation, managing complicated flows (this is where @br41nslug 's extension comes in, and then the Chat GPT token management and the updates required to @br41nslug 's extension.

**Comment by phazonoverload** [comment]
Lovely. Good scope of an article. We can pay $350 (USD) for this post. If that works for you, I'll mark it as approved, and the workflow is explained in the README of this repo.

The only other question I have is when you think a first draft might be doable (I'm not going to hold you to it - just trying to plan our publishing pipeline for the next few weeks).

**Comment by phazonoverload** [comment]
Hey @craigharman just checking if there's still appetite in writing this article.

**Comment by craigharman** [comment]
Absolutely, I responded via email but perhaps it was missed. I was completely swamped last week but should have some time this week to get started on a draft for you.

**Comment by phazonoverload** [comment]
Perfect, thanks!

**Comment by phazonoverload** [comment]
This work was completed in #5

**Comment by jaybharadia** [comment]
Hello @craigharman , seems like the [website](https://aiventure.craigharman.com) is down ⭕ due to some error. can you please check ?

**Comment by craigharman** [comment]
Hi Jay,

What was the error? Seems to be up?

https://aiventure.craigharman.com/

—
Craig

**Comment by jaybharadia** [comment]
![Screenshot_20231203-122216.jpg](https://github.com/directus-community/guest-authoring/assets/28944638/527ab6be-127c-4323-9360-ffe788a159ef)

500 server error. Attached screenshot
