### ISSUE TITLE
Getting Started With Directus and Astro

### ISSUE THREAD

**Issue by 0xJamin** [directus-community/guest-authoring#30]
### What is your idea?

In this article, I'll discuss how developers can use Directus to build web applications with Astro by building a blog app.

This will give readers an introduction to how they can integrate Directus with their Astro applications

### What are the key takeaways from your post?

Key features of this tutorial will include fetching data from Directus with Astro, displaying the data in Astro, and performing pagination in Astro

- Directus as the backend for managing content for the Astro blog
- Astro as the frontend of the application.

At the end of the article, readers will be equipped with the knowledge necessary to build an application with Directus and Astro

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Yes! This is a post I was actually hoping would be proposed by someone. I think this should follow the same format as the 'Build a Website with X' guides [here](https://docs.directus.io/guides/frameworks), but will be published on our developer blog. We can pay $350 for this post. 

If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by 0xJamin** [comment]
This will be available by the end of this week

**Comment by 0xJamin** [comment]
Hi @phazonoverload, This is ready. I was waiting for you to finish with the NextAuth article.

Creating a PR now
