### ISSUE TITLE
How to Deploy Directus to AWS

### ISSUE THREAD

**Issue by codejagaban** [directus-community/guest-authoring#31]
### What is your idea?

This tutorial will provide a practical step-by-step guide on how  to deploy a self-hosted instance of Directus to AWS using Amazon ECS

### What are the key takeaways from your post?

Readers will learn the following:
- How to set up Amazon ECS
- Set up an Amazon RDS (Relational Database Service) instance and connect
- Connect Directus to AWS Aurora DB
- Connect to s3 storage
- Deploy Directus to AWS and manage it with Amazon ECS

### What type of post is this?

Self-Hosting Guide

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Yes please! This topic would be great. We can pay $350 for this post. 

If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by 0xJamin** [comment]
This is also ready for review. I will create the PR by the end of today.
