### ISSUE TITLE
Directus Standard Guidelines and Best Practices for Developers

### ISSUE THREAD

**Issue by jaybharadia** [directus-community/guest-authoring#35]
### What is your idea?

In the realm of web development, adhering to standardized guidelines is not merely a suggestion but a strategic imperative, especially when orchestrating larger projects with collaborative teams. The proposed Directus Standard Guidelines, play a pivotal role in ensuring the seamless growth and scalability of projects. 

- This guide will demonstrate how setting up display interfaces can enhance the lives of data entry operators

- Guide will include practical examples and real-world scenarios

### What are the key takeaways from your post?

Reader will learn:

- Field and Relational Field Creation
Points to consider when defining fields for optimal data structure.
Best practices for establishing relational fields for efficient data relationships.

- Table Creation Best Practices

- Organizing Project Folders

- Naming Conventions for Files and Media
Best practices for naming files to ensure clarity and consistency.

- Reusable Tables

### What type of post is this?

Tips, Tricks, or Best Practice

### Country of residence

India

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thanks for this suggestion, but it's not one we want to pursue for our dev blog at the moment.
