### ISSUE TITLE
We are builing these - Together builds better futures for plugins

### ISSUE THREAD

**Issue by mikkeschiren** [directus-community/guest-authoring#36]
### What is your idea?

As I have been part of many open source communities during the years, one of the strongest I have been part of has been the Drupal community ("come for the code, stay for the community"), there are many things to be learned from there and other communities, like how to work together on plugins. Instead of building them by yourself or just employees from one company - we should find ways to work together on plugins, and improve the ones there are and help out where we can. And if we can't code, we can help to document it, and maybe together decide on how standard documentation should be done.

### What are the key takeaways from your post?

With some learnings from other open source communities we could have a stronger plugin community where we focus to maintain and improve plugins together. I will share some thoughts how we maybe could have a more vibrant plugin community, and how we could build engagement  - "We are building these" - instead of "I did this".

### What type of post is this?

Other

### Country of residence

Sweden

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thanks for submitting this idea, and happy new year! We're currently only interested in technical tutorials as part of our developer blog so this isn't the right fit for us.
