### ISSUE TITLE
Directus with Drizzle ORM

### ISSUE THREAD

**Issue by feliche93** [directus-community/guest-authoring#4]
### What is your idea?

I am huge fan of directus, especially the simple idea that everything is just simple tables in a db, but you got this super dope frontend, where you can create models and edit data in a super nice way.

I tried the directus SDK with Next13 before but wasn't super super happy with it.

1) You have to generate the data model types yourself with some third party library
2) The version I used depended on axios which is not compatible with next.js edge runtimes
3) The query logic seemed complicated especially for nested data and the types were not always working 100% well

Since I am huge fan of Drizzle ORM, I actually used the drizzle-inspect feature on my existing neon serverless db to generate the schema and all the types and created my own custom directus drizzle client.

With that querying the tables is super easy if you understand sql and you get perfect type completion. I wrote some content before on why I think drizzle is a game changer: https://www.felixvemmer.com/blog/drizzle-orm-boosting-developer-productivity/

I wanted to share may learning with the community for the blog and subsequent content I am building for backlinkgpt.com: https://www.backlinkgpt.com/blog/link-building-ai.

The blogpost would cover:

1. Setting up Blog Post models (blogposts, authors, categories etc.) -> More breeve since other tutorials cover this well!
2. Installing drizzle orm and using inspect feature to pull all models from directus and gettign the typescript client ready
3. Creating a custom "schema" clean up fucntion that removes some errors from the generation
4. Implemenation of rendering logic in Next13 Server components
5. Discussion of drawbacks (e.g. edge runtime, vs native sdk operations that are harder to rebuild)

### What are the key takeaways from your post?

- How to get typesafe directus client that makes querying data super easy
- How to fix the generated schema with errors
- Advantages and disadvantages of this appraoch
- How to implement many-2-any and other data models for the typical blog content

### What type of post is this?

Full Project Build with Directus

### Country of residence

Germany

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Hey @feliche93 thanks for submitting this idea and for the kind words about the project. 

At the moment, this idea is not one that we want to further pursue for our developer blog, but we'd be open to hearing any other ideas you have as new issues. Checked out your blog and you're writing style is good. 👍🏻 

As a side note, I hope that our new SDK fixes many of these points for frustration for you and others - sounds like it may do! 😄

**Comment by feliche93** [comment]
Hey @phazonoverload thanks for the feedback. I just checked the docs and despite saying in the beginning:

> TypeScript first: The SDK provides a robust and type-safe development experience

Later on it says you need to create those types yourself:

<img width="756" alt="CleanShot 2023-09-17 at 09 52 45@2x" src="https://github.com/directus-community/guest-authoring/assets/29236063/31e4d5e2-5425-49df-8e68-983a8c860ada">

It would be great if you could add a link to this callout since I only found this one later in another section:

<img width="777" alt="CleanShot 2023-09-17 at 09 57 14@2x" src="https://github.com/directus-community/guest-authoring/assets/29236063/f47f3fe2-141d-41ba-8cb5-362cae1d2c4a">

I think personally maintaining this yourself and manually creating even with ChatGPT and things alike is too tedious. Maybe this is just being me lazy, but I think there's a strong case for using Drizzle for Data and Directus SDK for other things like websocket, auth etc. So I will publish this post then instead on my blog :) 

I appreciate the quick feedback and reply and look forward to more awesome articles on the new blog!

Cheers, 

Felix

**Comment by feliche93** [comment]
@phazonoverload just published it here, hopefully explains a bit better my thoughts! https://www.felixvemmer.com/blog/drizzle-orm-directus-typescript-sdk/

**Comment by lpkobamn** [comment]
needs update
