### ISSUE TITLE
How to Implement Live-Preview in Astro with Directus

### ISSUE THREAD

**Issue by codejagaban** [directus-community/guest-authoring#43]
### What is your idea?

In this article, I'll discuss how developers can implement a live preview in Directus when working with the Astro framework.

This will introduce readers to how they can integrate Directus live-preview feature with their Astro applications.

### What are the key takeaways from your post?

Key features of this tutorial will include fetching data from Directus with Astro, setting up the preview URL, previewing contents in Directus, and displaying the data in Astro.

At the end of the article, readers will be able set up Directus live-preview feature for any Astro project of their choice.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This is good - let's get other posts you've pitched done first, and then swing back around to this after.
