### ISSUE TITLE
Getting Started With  Directus and Remix

### ISSUE THREAD

**Issue by codejagaban** [directus-community/guest-authoring#44]
### What is your idea?

In this article, I'll discuss how developers can use Directus to build web applications with Remix by building a blog app.

This will give readers an introduction to how they can integrate Directus with their Remix applications

### What are the key takeaways from your post?

Key features of this tutorial will include fetching data from Directus with Remix, displaying the data in Remix, and performing pagination in Remix

Directus as the backend for managing content for the Remix blog
Remix as the frontend of the application.
At the end of the article, readers will be equipped with the knowledge necessary to build an application with Directus and Remix

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Could this follow the same format as #37? And when do you think you could have a first draft by? Super up for the topic, and we can pay $350 for this post. 😄

**Comment by codejagaban** [comment]
This will be ready by next week.

**Comment by phazonoverload** [comment]
Fabulous
