### ISSUE TITLE
Deploying Directus to Render

### ISSUE THREAD

**Issue by vasfvitor** [directus-community/guest-authoring#46]
### What is your idea?

Create a guide showing how to self host on Render.com. This guide will go though writing a render blueprint file (render.yml) file. And, perhaps explain how it's possible to do the same deployment by utilizing the UI, step by step, and the difference between both.

### What are the key takeaways from your post?

How to write a `render.yml` file to programmatically deploy Directus with PostgreSQL to Render
Understand how `render.yml` file relate to Render's UI
Takeaways about data persistence

### What type of post is this?

Self-Hosting Guide

### Country of residence

Brazil

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Hey! Thanks for submitting this but we won't be going ahead with it at the moment. We have enough PaaS posts written or in the works.

**Comment by vasfvitor** [comment]
Yeah, I noticed that. I wanted to write something more focused on Directus (like flows) but I'm haven't got any ideas. On a side note I thought about a self-host checklist but I'm not confident enough to make it, anyways... thanks!
