### ISSUE TITLE
Gatsby and the Directus JavaScript SDK

### ISSUE THREAD

**Issue by alvinometric** [directus-community/guest-authoring#48]
### What is your idea?

After chatting with @phazonoverload , it turns out Gatsby is the major framework missing from the [Directus guides](https://docs.directus.io/guides/frameworks). My website used to run on Gatsby so I used it a lot.

### What are the key takeaways from your post?

How to use Gatsby to build a website with the Directus SDK, similarly to [this post](https://docs.directus.io/blog/getting-started-directus-sveltekit.html)

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

UK

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Yup sounds good. we can pay $350 for this post. 

If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by alvinometric** [comment]
Thanks Kevin, 
I'll have a draft ready for you at the end of next week (January 19th)
