### ISSUE TITLE
Getting Started With Directus and Hugo

### ISSUE THREAD

**Issue by Marktawa** [directus-community/guest-authoring#54]
### What is your idea?

This tutorial will show you how to integrate Hugo Static Site Generator with Directus. I will build a static blog similar to the framework guides in the Directus docs.

### What are the key takeaways from your post?

Readers will learn:
- How to set up a Hugo project to fetch data from a remote backend.
- How to create data collections in a Directus project.
- How to set up Directus as a backend using a REST API.
- How to serve and build a Hugo static site.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Zambia

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We can pay $250 for this post - it should follow the same format as our other 'Getting Started with Directus and X' posts on our dev blog. If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule.

The process is detailed in the README of this repo 😄

**Comment by Marktawa** [comment]
Ok thanks. I will have it done by Friday.

**Comment by phazonoverload** [comment]
There is no rush - we won't be posting this until March. I won't get around to reviewing it right away if you submit on Friday so feel free to take a few weeks on this. Shall we set a target first draft date on Feb 2? 😄
