### ISSUE TITLE
Building a Real-time Chat Application with Directus and Socket.io

### ISSUE THREAD

**Issue by GeoSegun** [directus-community/guest-authoring#58]
### What is your idea?

This article aims to guide readers and developers through building a real-time chat application using Directus as the headless CMS for data storage and Socket.io for real-time client communication.
This article will provide a step-by-step approach to setting up the backend server using Node.js and Express, integrating it with Socket.io for WebSocket communication, and utilizing Directus as a backend for storing and retrieving chat messages.
Here is the proposed outline:
- Setting up Directus
- Building the Socket.io Server: I will be creating a Node.js server using Express and Socket.io to handle real-time communication between clients.
- Integrating with Directus: I will use Axios to send and receive messages from the Directus API, allowing the chat messages to be stored and retrieved.
- Setting up frontend: we'll create a basic HTML frontend with Socket.io client-side integration to enable real-time communication and display of chat messages.

### What are the key takeaways from your post?

Readers will learn how to integrate Directus, a headless CMS, with Socket.io to build a real-time chat application. This tutorial covers setting up the backend server, handling communication using Socket.io, and utilizing Directus for storing and retrieving chat messages, providing valuable insights into combining headless CMS and real-time communication technologies.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thanks for submitting this idea. Doesn't make sense for us as we have a direct WebSockets interface with Directus Realtime.

**Comment by GeoSegun** [comment]
Hello Kevin,
 I can adjust this topic instead I will leverage Directus Realtime, which offers a direct WebSockets interface. The backend server will be adjusted to communicate directly with Directus Realtime for handling real-time communication. Finally, the frontend will be modified to interact with these WebSockets to create the chat application.
 
 Those this make sense?

**Comment by phazonoverload** [comment]
This project is already in our documentation with three variants. Thanks for submitting the idea, but we won’t be going ahead with it.
