### ISSUE TITLE
Building a Modern eCommerce Site with Directus and Next.js

### ISSUE THREAD

**Issue by Claradev32** [directus-community/guest-authoring#62]
### What is your idea?

In this tutorial, the readers will learn how to build a modern eCommerce site using Directus and Next.js. The focus will be on leveraging Directus as a backend to manage eCommerce content such as product listings, descriptions, and images, while utilizing the powerful capabilities of Next.js to build a fast, server-side-rendered front-end.

### What are the key takeaways from your post?

This tutorial will cover the following:
- Introduction 
- Setting Up Next.js with Directus
- Creating and Managing eCommerce Content in Directus
- Fetching Data from Directus in Next.js
- Building Dynamic Product Pages in Next.js
- Optimizing for Performance and SEO
- Conclusion

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by Claradev32** [comment]
Hi @phazonoverload,
I'm interested in writing on this topic for yoru blog.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. 

This is due to the fact that this is effectively a CMS tutorial with a slightly different narrative, and we have plenty of CMS posts at the moment.

Please feel free to submit additional ideas in future.
