### ISSUE TITLE
Build an Interactive Live Map using Leaftlet.js, Next.js and Directus

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [directus-community/guest-authoring#64]
### What is your idea?

In this article, we will build a map-powered application using LeafletJs, Next.js, and Directus. 

The application will show features of LeafletJs, such as markers using latitudes and longitudes, custom markers, popups, and vector layers to display a user's coverage. Directus will allow users to store data, provide real-time updates to place details using the WebSocket interface and enable real-time updates in our Nextjs map. We will use the REST API feature of Directus to fetch, update, and delete places from the maps in real time.

### What are the key takeaways from your post?

- Readers will understand how to integrate Leaflet.js in their Next.js application.
- They will learn how to build a map-powered application.
- Readers will learn about Directus Websockets.
- Readers will learn how to make CRUD requests to Directus API

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting an idea for our guest blog.
            
We work through new ideas every few weeks as we put together our content schedule. This means you may not get an immediate response as to whether your idea has been accepted, or any follow-up questions we have to clarify your idea. 

If your idea is accepted, we will provide a deadline for first draft and how much we can pay you for the post. You will have a few days to confirm whether you are still able and willing to write the post. 

If you have any questions in the meantime, feel free to add a comment to this issue.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We have a mapping layout at the moment which can poll for updates, with plans to implement Realtime throughout the Data Studio in the future. Please feel free to submit additional ideas in future.
