### ISSUE TITLE
Getting Started With Directus and Eleventy

### ISSUE THREAD

**Issue by Marktawa** [directus-community/guest-authoring#68]
### What is your idea?

My idea is a tutorial showcasing how you can build a website using Eleventy and Directus. The format of the tutorial will be similar to the framework guides in the Directus docs.

### What are the key takeaways from your post?

The reader will learn:
- How to integrate the Directus SDK into the Eleventy website build flow.
- How to set up a Directus project (collections, fields, items, access control) API
- How to fetch data (pages, posts, images, etc) using the Directus SDK in Eleventy

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Zambia

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thanks for submitting this idea. It's already under development by our own team (not as part of the guest author program).
