### ISSUE TITLE
The European Accessibility Act. What you should know.

### ISSUE THREAD

**Issue by robertkeus** [directus-community/guest-authoring#73]
### What is your idea?

I would like to write an article about the upcoming European Accessibility Act in 2025.

### What are the key takeaways from your post?

- Understanding of the European Accessibility Act: Readers will learn about the purpose, scope, and key components of the Act, providing them with a thorough understanding of this significant legislation.
- Technical Requirements for Compliance: This section would outline the specific technical measures and standards that businesses and organizations need to implement to adhere to the Act. It would include details on digital accessibility, such as website and app design, as well as physical accessibility in terms of building infrastructure and product design.- Awareness of Accessibility Issues: The article will highlight the importance of accessibility in various aspects of society, helping readers recognize the challenges faced by individuals with disabilities and the need for inclusive practices.
- Impact on Businesses and Organizations: Readers will understand how the Act affects different sectors, learning about the adjustments and innovations businesses must adopt to comply with the new standards.
- Benefits for People with Disabilities: The article will elucidate how the Act will improve the lives of individuals with disabilities, offering insights into the real-world impact of such legislation.
- Critical Analysis Skills: By discussing challenges and criticisms of the Act, the article will encourage readers to critically analyze legislation, understanding both its benefits and potential drawbacks.
- Preparation Strategies: For businesses and organizations, the article will provide practical advice on preparing for the Act’s implementation, teaching planning and adaptation skills.
- Resource Identification: Readers will learn how to identify and utilize available resources and support systems to aid in compliance and understanding of the Act.
- Broader Application of Accessibility Principles: The skills and knowledge gained will not only be applicable to the European Accessibility Act but also to understanding and implementing accessibility principles in various contexts, encouraging inclusive practices beyond legal requirements.

### What type of post is this?

Tips, Tricks, or Best Practice

### Country of residence

Netherlands

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Our guest author program is for technical, code-based tutorials so this isn't a good fit. Please feel free to submit additional ideas in future.

**Comment by robertkeus** [comment]
Uhm... okay... Accessibility is for 90% technical. And I think a lot of people will want to know what you can do to use Directus in combination with the WCAG to compy to all the accessibility guide lines world wide, like the ADA and the European Accessibility Act.

**Comment by phazonoverload** [comment]
But not in the way the idea has been presented - which I take to be a resource to help people understand the EAA, rather than guidelines for implementation. Even then, the topic is far enough removed from Directus that I don't expect us to become an authoritative voice on this topic. 

Accessibility is very close to my heart, but we also work with a defined scope for what we can accept - the category 'Tips, Tricks, and Best Practice' is more about Directus usage. Before I would feel comfortable touch accessibility as a topic we would ever educate on, I would want further work to happen to make the Directus Data Studio more accessible. 

I hope this provides some more context around the decision. Have a lovely rest of your day.
