### ISSUE TITLE
Directus vs Wordpress: Which headless CMS is best

### ISSUE THREAD

**Issue by uma-victor1** [directus-community/guest-authoring#76]
### What is your idea?

Selecting a content management system (CMS) is a crucial decision for software development, and developers play a pivotal role in choosing the right one. Directus and WordPress are two popular CMS platforms often considered. 
By the end of this article, you will understand which CMS suits your team’s needs and development requirements. 

### What are the key takeaways from your post?

- Which CMS to choose for your team
- Comparison with Wordpress to highlight Directus strength
- Links to resources for further learning about Directus

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Our guest author program is for technical, code-based tutorials so this isn't a good fit. Please feel free to submit additional ideas in future.
