### ISSUE TITLE
How to Build a Landing Page With React-Native: Step-By-Step Guide

### ISSUE THREAD

**Issue by uma-victor1** [directus-community/guest-authoring#77]
### What is your idea?

In the fast-paced world of mobile apps, where competition is fierce, businesses are constantly evolving for the attention of potential users. Picture a product-focused landing page as the star of the show—a dedicated space meticulously designed to showcase a specific app, grabbing interest, educating users, and ultimately driving downloads. In this article you will learn how to use Directus in building a React-Native App

### What are the key takeaways from your post?

- Building a fullstack application with React-Native and Directus
- Learn how to use the Directus Platform and SDK
- Learn how to manage roles
- Links to relevant resources

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We don't have a lot of community or customer demand for React Native content at the moment. If that changes, I will let you know. 

Please feel free to submit additional ideas in future.
