### ISSUE TITLE
Build an Automated Shopping List with Directus

### ISSUE THREAD

**Issue by binaryben** [directus-community/guest-authoring#83]
### What is your idea?

Build an MVP of an automatically updated shopping list for smart homes. The goal is to use a RPi Zero 2W with a barcode reader attached to scan grocery items as you throw them out. I plan to have basic inventory tracking to know when "stock" is low.

NB: I plan to use the [SSO authentication setup described in this post proposal](https://github.com/directus-community/guest-authoring/issues/82) as part of the project.

### What are the key takeaways from your post?

Some of the key take aways include:

* Working with the Directus SDK on an IoT device[^1]
* Data modelling basic inventory tracking and management (locations, items, SKUs, etc)
* Integration with other services (i.e. for notifications)
* Building a custom module for the shopping list
* Working with flows

[^1]: May end up working directly with the API depending on which language I use on the RPi Zero 2W

### What type of post is this?

Full Project Build with Directus

### Country of residence

Australia

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. I know this may be disappointing as you effectively submitted a two-parter, but this project is a little abstract for most of our users. Please feel free to submit additional ideas in future.
