### ISSUE TITLE
Integrating Directus with Waku the new React framework

### ISSUE THREAD

**Issue by Claradev32** [directus-community/guest-authoring#87]
### What is your idea?

Waku is a React.js framework that has been getting massive traction from developers. This tutorial will cover how to combine the framework to build a minimalistic React application/

### What are the key takeaways from your post?

This tutorial will cover:
- What is Waku?
- Why use Waku and Directus?
- Setup New Waku application
- Build UI interface
- Setup Model on Directus
- Create App routes
- Server-Side data fetching
- Implementing State Management

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We haven't observed the demand for this framework yet. Please feel free to submit additional ideas in future.
