### ISSUE TITLE
Getting Started with Directus and iOS

### ISSUE THREAD

**Issue by HarshpalBhirth** [directus-community/guest-authoring#9]
### What is your idea?

Getting Started with Directus and iOS  

### What are the key takeaways from your post?

- Displaying a list of items, and a detail page
- Authentication: create account, login, logout
- Creating a new item using a form 

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

United Kingdom 

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Already scoped this out with you aside from this repo. Sounds good to me. Let's shoot for end-Oct first draft. Ping me if you need help.

**Comment by phazonoverload** [comment]
As we have spoken about off-platform, we'll remove auth from this post and drop the payment to $350. Auth can be the focus of a separate article.
